### ISSUE TITLE
 Not specify an extension not open

### ISSUE THREAD

**Issue by yueduz** [zsytssk/open-path#1]
Not specify an extension not open

import '../scss/pure.scss'
import React from 'react'
import { render } from 'react-dom'
import { Provider } from 'react-redux'
import App from './containers/App'
import configureStore from './configureStore'

**Comment by zsytssk** [comment]
what are you mean?
如果你是中国人直接说中文吧

**Comment by yueduz** [comment]
不好意，那个是用google翻译的。我意思是说路径没有扩展名就不能自动打开了。

**Comment by yueduz** [comment]
文件本身是有扩展名的，但是我在代码里不用把扩展名写出来。

**Comment by zsytssk** [comment]
把你的文件结构发给我，我测试下
想这样的结构
-| folder
	-| subfolder
		-| file2.extension
	-| file1.extension

**Comment by zsytssk** [comment]
你把你的目录结构发给我 我测试测试，目录结构像这样
文件夹
├── 子文件夹
├────── 文件.扩展名
├────── 文件.扩展名
├── 文件.扩展名

**Comment by yueduz** [comment]
我现在外出了，回去了发给你

**Comment by yueduz** [comment]
我刚试了下，又能开了。可能是我之前路径不对。
谢谢
另在请教一个问题，有没有快捷键可直接选择引号中的内容？

**Comment by zsytssk** [comment]
你是搜索下 expand-selection-to-quotes 插件
建议你到google 或者 https://atom.io/packages/ 中搜索 或者加一个atom qq 群

**Comment by yueduz** [comment]
发现更好用的插件 hyperflick 能打开函数所在文件并且定位到函数

张世阳 notifications@github.com于2016年3月3日周四 15:56写道：
